AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >
  Creates an API Gateway REST API with two Lambda functions that interact with a DynamoDB table.

Parameters:
  TableName:
    Type: String
    Description: The name of the DynamoDB table to create or use.
    Default: home_page
  AttributeName:
    Type: String
    Description: The name of the partition key of the DynamoDB table.
    Default: record_id

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ReturnCountFunction: #Returns the visitor count from the specified DynamoDB table.
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python/src/return_count/
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /get
            Method: GET
      Handler: lambda_get_visitor_count.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Runtime: python3.8
      
  IncrementCountFunction: #Increments the visitor count in the specified DynamoDB table.
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python/src/increment_count/
      Events:
        PutRequest:
          Type: Api
          Properties:
            Path: /put
            Method: GET
      Handler: lambda_increment_visitor_count.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName      
      Runtime: python3.8
      
  
  DynamoDBTable: #A table to store the visitor count.
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: !Ref AttributeName
          AttributeType: "S"
      KeySchema:
        - AttributeName: !Ref AttributeName
          KeyType: "HASH"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CrcApiInfraAPI:
    Description: "API Gateway endpoint URL for Prod stage for Increment and Return Count functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  IncrementCountFunction:
    Description: "Increment Lambda Function ARN"
    Value: !GetAtt IncrementCountFunction.Arn
  ReturnCountFunction:
    Description: "Return Lambda Function ARN"
    Value: !GetAtt ReturnCountFunction.Arn
  IncrementCountFunctionIamRole:
    Description: "Implicit IAM Role created for Increment Count function"
    Value: !GetAtt IncrementCountFunctionRole.Arn
  ReturnCountFunctionIamRole:
    Description: "Implicit IAM Role created for Return Count function"
    Value: !GetAtt ReturnCountFunctionRole.Arn
